apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: influxdb
  name: influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: influxdb
  template:
    metadata:
      labels:
        app: influxdb
    spec:
      containers:
      - image: influxdb
        name: influxdb
        imagePullPolicy: Never
        ports:
          - containerPort: 8086
        volumeMounts:
          - name: pv-influxdb
            mountPath: /var/lib/influxdb
        livenessProbe:
          exec:
            command:
              - ./restart.sh
          initialDelaySeconds: 2
          periodSeconds: 2
      volumes:
        - name: pvc-influxdb
          persistentVolumeClaim:
            claimName: pvc-influxdb