apiVersion: v1
kind: PersistentVolume
metadata:
    name: pv-influxdb
    labels:
        type: local
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: /mnt/base/influxdb