apiVersion: v1
kind: PersistentVolume
metadata:
    name: pvc-influxdb
    labels:
        app: influxdb
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi