apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      restartPolicy: Always
      containers:
      - image: mysql
        name: mysql
        imagePullPolicy: Never
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: pv-mysql
            mountPath: /var/lib/mysql
        livenessProbe:
          exec:
            command:
              - ./restart.sh
          initialDelaySeconds: 2
          periodSeconds: 2
      volumes:
        - name: pvc-mysql
          persistentVolumeClaim:
            claimName: pvc-mysql