apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: pvc-mysql
    labels:
        app: mysql
spec:
    accessModes:
        - ReadWriteMany
    resources:
        requests:
            storage: 1Gi
    