apiVersion: v1
kind: Service
metadata:
  labels:
    app: grafana
  name: grafana
  annotations:
    metallb.universe.tf/allow-shared-ip: shared 
spec:
  ports:
    - name: http
      port: 3000
      protocol: TCP
      targetPort: 3000
  selector:
    app: grafana
  type: LoadBalancer