apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: nginx
        name: nginx
        imagePullPolicy: Never
        ports:
          - containerPort: 80
          - containerPort: 443
        livenessProbe:
          exec:
            command:
              - ./restart.sh
          initialDelaySeconds: 2
          periodSeconds: 2