apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: phpmyadmin
  name: phpmyadmin
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phpmyadmin
  template:
    metadata:
      labels:
        app: phpmyadmin
    spec:
      containers:
      - image: phpmyadmin
        name: phpmyadmin
        imagePullPolicy: Never
        ports:
          - containerPort: 5000
        livenessProbe:
          exec:
            command:
              - ./restart.sh
          initialDelaySeconds: 2
          periodSeconds: 2