apiVersion: v1
kind: Service
metadata:
  labels:
    app: wordpress
  name: wordpress
spec:
  ports:
    - name: wordpress
      port: 5050
      protocol: TCP
      targetPort: 5050
  selector:
    app: wordpress
  type: LoadBalancer