apiVersion: v1
kind: Service
metadata:
  labels:
    app: telegraf
  name: telegraf
  annotations:
    metallb.universe.tf/allow-shared-ip: shared 
spec:
  ports:
    - name: http
      port: 8094
      protocol: TCP
      targetPort: 8094
  selector:
    app: telegraf
  type: LoadBalancer