apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ftps
  name: ftps
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - image: ftps
        name: ftps
        imagePullPolicy: Never
        ports:
          - containerPort: 21
          - containerPort: 21000
        livenessProbe:
          exec:
            command:
              - ./restart.sh
          initialDelaySeconds: 2
          periodSeconds: 2