apiVersion: v1
kind: Service
metadata:
  labels:
    app: ftps
  name: ftps
  annotations:
    metallb.universe.tf/allow-shared-ip: shared 
spec:
  ports:
    - name: ftps
      port: 21
      protocol: TCP
      targetPort: 21
  selector:
    app: ftps
  type: LoadBalancer